### ISSUE TITLE
Is the demogod repo available to view

### ISSUE THREAD

**Issue by dsarfati** [netlify/actions#13]
We are moving our mono repo (with 3 different netlify sites) over to Github Actions and i'm looking for any examples that would help. The `demogod` repo seems like it would be the perfect example for the community, but it is a private repo. Is there any way we could have access to this repo or one very similar? Great talk/demo @rafaelconde!!

**Comment by rafaelconde** [comment]
@dsarfati I just made the repo public — but keep in mind that it hasn't been updated since that demo 👇 
https://github.com/rafaelconde/demogod

**Comment by dsarfati** [comment]
Thanks so much for making this public. I will take a look and see what I can pull into our workflows. Looking forward to future updates from the netlify team!
