### ISSUE TITLE
Redirecting output is failing

### ISSUE THREAD

**Issue by antoniosb** [netlify/actions#15]
After this commit b56d0f2a63a4f4f536cb3d300831d17f3d56cf53 it's not possible to redirect the output of the entrypoint command. 

Seems like everything passed through is parsed as args, see the examples below:

![image](https://user-images.githubusercontent.com/2124310/66769865-95f1e180-ee8c-11e9-9464-a652153cc848.png)

![image](https://user-images.githubusercontent.com/2124310/66769888-a1dda380-ee8c-11e9-9e59-5c635975b524.png)

This may be because the removal of the `sh -c` that wrapped the command before.

**Comment by eMerzh** [comment]
i think you can now try with latest version and it should fix your issues :)

**Comment by antoniosb** [comment]
Yeah, it's working now! Thanks to #24  🎉
