### ISSUE TITLE
Clarify GITHUB_TOKEN for build action

### ISSUE THREAD

**Issue by tschaub** [netlify/actions#33]
I see that the build action uses the `GITHUB_TOKEN` in an `Authorization` header for a request to the Netlify API:
https://github.com/netlify/actions/blob/645ae7398cf5b912a3fa1eb0b88618301aaa85d0/build/entrypoint.sh#L20-L24

I had guessed based on the name that `GITHUB_TOKEN` might be a [personal access token](https://github.com/settings/tokens/new) with access to the GitHub repo where I am running the action.  But seeing it used for the Netlify API, I wonder if instead it would be a token created for access to the Netlify site (which makes a bit more sense).

I'd be happy to create a pull request for the docs to help clarify how to create this `GITHUB_TOKEN` and what scope it should have if someone could clarify that for me.

**Comment by tschaub** [comment]
It looks like this is indeed a GitHub personal access token.  I created one with `public_read` scope and the [build action](https://github.com/openlayers/archive/runs/702686611) succeeded.  I was hoping this would result in a deploy of the site, but it looks like that didn't happen.  Maybe I need to look for a deploy action...

**Comment by prateekkumarweb** [comment]
The token `GITHUB_TOKEN` is available in GitHub Actions. You don't have to create a personal access token.
See https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#about-the-github_token-secret for more details.

**Comment by tschaub** [comment]
Thank you for the clarification!

**Comment by tahirmahmudzade** [comment]
this probably not related but I'm eager to learn about it. Is it possible to obtain access to user's netlify account using GitHub access token? I would like to authorize user using Github oauth and get the access token and use it to create a site on user's related netlify account via Netlify Api?
