### ISSUE TITLE
[netlify/actions/build]: "FAILED Publish" Error

### ISSUE THREAD

**Issue by vinaypuppal** [netlify/actions#4]
I am trying to deploy a `preact-cli` project but getting this error

```sh
Status: Downloaded newer image for gcr.io/github-actions-development/action-runner:latest
Deploying

### FAILED Publish 21:04:18Z (10.663s)
```

### I am using below `main.workflow`

```
workflow "Publish on Netlify" {
  on = "push"
  resolves = ["Publish"]
}

action "Publish" {
  uses = "netlify/actions/build@master"
  secrets = ["GITHUB_TOKEN"]
  env = {
    NETLIFY_CMD = "npm run build"
    NETLIFY_DIR = "build"
  }
}
```

**Comment by kitop** [comment]
Hi @vinaypuppal 
Is this still happening? Do you have a repo to reproduce this?

**Comment by vinaypuppal** [comment]
Hi @kitop 

Yes, it's still happening.
This is the repo: https://github.com/vinaypuppal/test-netlify-actions
Logs from this repo: https://github.com/vinaypuppal/test-netlify-actions/runs/44453570

**Comment by kitop** [comment]
Hi @vinaypuppal, thanks for the details! 
Just pushed a fix for the issue, it should be working again. Let us know if any other issues!

**Comment by vinaypuppal** [comment]
Thanks, @kitop for the fix.

I tested it
1. It's working when I don't set `NETLIFY_SITE_ID` and its creating new site in netlify dashboard as expected. 
1. **But when I add `NETLIFY_SITE_ID` to workflow it's not triggering a build in netlify dashboard**. There are no errors in workflow log

```
workflow "Publish on Netlify" {
  on = "push"
  resolves = ["Publish"]
}

action "Publish" {
  uses = "netlify/actions/build@master"
  secrets = [
    "GITHUB_TOKEN",
    "NETLIFY_SITE_ID",
  ]
}
```

**Comment by kitop** [comment]
Hi @vinaypuppal 
When using `NETLIFY_SITE_ID`, is the site you're pointing to linked to the repo already? Is it the same site created in point 1.?

**Comment by vinaypuppal** [comment]
>  Is it the same site created in point 1.?

Yes


> When using NETLIFY_SITE_ID, is the site you're pointing to linked to the repo already?

Yes, in netlify dashbaord under `settings -> general -> Site details` I see it linked to the repo.

**Comment by kitop** [comment]
@vinaypuppal thanks for the responses!
There was a small issue on how we were dealing with those requests and now deployed a fix for it. It should now be working when you run it again. Let us know if any further issues!

**Comment by vinaypuppal** [comment]
@kitop It's working now. Thanks
