### ISSUE TITLE
How can I use my deploy URL in subsequent actions?

### ISSUE THREAD

**Issue by trevorblades** [netlify/actions#9]
This is my first time using GitHub actions, and I'm trying to create a workflow that creates a deploy preview on Netlify, and then runs a broken link checker on the deploy preview. Unfortunately, I'm having a hard time understanding how I'd be able to pass along information about the deploy to the next step in my workflow.

**Comment by kitop** [comment]
Mhm... good question!
I'm not sure if it's possible to hook out the output of one action to the input of another one. If you know which site you're deploying to (ie: have the `NETLIFY_SITE_ID` env variable set) then you can add another variabl with the site domain so the broken link checker can use it.

This could be a good use for `repository_dispatch` events (https://developer.github.com/actions/managing-workflows/triggering-a-repositorydispatch-webhook/) but unfortunately, it only allows to customize the `event_type` payload key now, not add any other custom fields :(

**Comment by trevorblades** [comment]
That's what I figured, but I'm glad I asked. Thanks for your thoughts!

The only issue with the first approach is that I'd want to check links on deploy previews before they get deployed to production. No worries though, I'm sure that it's possible to achieve this behaviour by using the Netlify API in a custom CI script.

**Comment by IvanJosipovic** [comment]
This is actually supported.

I have it working here:
 - Workflow: https://github.com/IvanJosipovic/KubeUI/blob/master/.github/workflows/cicd.yml
 - Updated action: https://github.com/IvanJosipovic/actions/blob/dev3/cli/entrypoint.sh

If anyone is interested, I could provide a PR.

**Comment by trevorblades** [comment]
That's awesome @IvanJosipovic! If you could, that would be awesome. In the mean time, I can just use the action that you created.

**Comment by IvanJosipovic** [comment]
Added PR https://github.com/netlify/actions/pull/11

@trevorblades use IvanJosipovic/actions@master for the latest version.
